### ISSUE TITLE
could you help add JMA indicador?

### ISSUE THREAD

**Issue by iSkywalker168** [MerlinR/Hexital#22]
it seems JMA behaves better than EMA in some situations. and pandas_ta already has JMA indicator(pandas_ta.jma).
here are the formula info:
https://br.tradingview.com/script/nZuBWW9j-Jurik-Moving-Average/
http://jurikres.com/catalog1/ms_ama.htm

![image](https://github.com/user-attachments/assets/1bf07539-65e8-4b86-b9e0-b2d6fac1fac0)
![image](https://github.com/user-attachments/assets/d5c5a26e-6834-4b43-a6a2-63a879a0eec3)

**Comment by MerlinR** [comment]
Yea can look to add JMA, (https://c.mql5.com/forextsd/forum/164/jurik_1.pdf)

**Comment by iSkywalker168** [comment]
> Yea can look to add JMA, (https://c.mql5.com/forextsd/forum/164/jurik_1.pdf)

sure, i will try to implement incremental JMA indicator, if finished testing, i will post my JMA draft here.
but my programming skill is not good, neither my math, it might take some time for me to do it.

**Comment by iSkywalker168** [comment]
did I misunderstand you? you wanna me add JMA to Hexita?

**Comment by MerlinR** [comment]
@iSkywalker168, I have added JME, It's very accurate to pandas_ta, although some decimal places may differ. This implementation will also create JMA with only one candle available, so first few (period length) will be volatile.

Closing this for now, can be re-opened if needed.
